title: Joe Shirey's Blog
email: your-email@example.com
description: >-
  A modern blog exploring technology, design, and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.joe-shirey.com" # the base hostname & protocol for your site
twitter_username: joeshirey
github_username:  joeshirey

# Build settings
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jemoji
  - jekyll-archives
  - jekyll-gist

# Custom settings
google_analytics: G-FP2RTDC8RQ
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugin Configurations
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
